# Generated by Django 5.2.1 on 2025-08-25 09:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GlassPack_site', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='comment',
            field=models.TextField(max_length=1000, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
